version: '3.8'

services:
  app_personas:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://dpg-cqfj522ju9rs73bu00u0-a.oregon-postgres.render.com:5432/crud_personas_jgnm
      DB_USERNAME: admin
      DB_PASSWORD: TIdDhBw7I6e8ZLws9K2cyYQs6D1qh5T8
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge